### ISSUE TITLE
Controllare Twitch player per diretta 

### ISSUE THREAD

**Issue by f4nu** [ItalianSpeedrunCommunity/isc-web#3]
In [index.html](src/index.html) c'è un embed che parte in automatico solo quando il canale è in diretta, con il JS nel footer.

Nel provare a farlo funzionare ho cambiato l'inizializzazione da `Twitch.Embed` a `Twitch.Player`, per poter usare l'evento `Twitch.Player.ONLINE` e nascondere la hero e mostrare il player.

Funziona, ma ci sono un bel po' di errori in console e dopo qualche refresh si viene bloccati da Twitch (HTTP 429).

Vorrei esplorare qualche altra soluzione, in particolare capire se si può tornare all'utilizzo di `Twitch.Player` e se l'evento `Twitch.Embed.VIDEO_PLAY` parte in automatico in caso il canale fosse online.

[Documentazione Twitch embed everything](https://dev.twitch.tv/docs/embed/everything/)
```javascript
var embed = new Twitch.Embed('twitch-embed', {
  channel: 'monstercat'
});

embed.addEventListener(Twitch.Embed.VIDEO_READY, function() {
  console.log('The video is ready');
});
```

**Comment by LorenzoBellomo** [comment]
gdq fa così quindi va bene così
